"""Run against tests/serve_preview.py, never against real farmer records."""
import argparse
import json
from pathlib import Path

from playwright.sync_api import sync_playwright, expect


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--url', default='http://127.0.0.1:8001')
    parser.add_argument('--executable', required=True)
    args = parser.parse_args()
    artifacts = Path(__file__).resolve().parents[1] / 'private_data' / 'browser_qa'
    artifacts.mkdir(parents=True, exist_ok=True)
    errors = []
    with sync_playwright() as playwright:
        browser = playwright.chromium.launch(headless=True, executable_path=args.executable)
        page = browser.new_page(viewport={'width':1440,'height':1000}, reduced_motion='reduce')
        page.on('pageerror', lambda error: errors.append(str(error)))
        page.goto(args.url+'/login')
        page.locator('#username').fill('preview-farmer')
        page.locator('#password').fill('Preview farmer password!')
        page.get_by_role('button', name='Sign in', exact=True).click()
        expect(page.get_by_role('heading', name='Dashboard')).to_be_visible()
        expect(page.get_by_role('button', name='Benchmarks', exact=True)).to_have_count(0)
        assert 'yolo' not in page.locator('body').inner_text().lower()
        page.screenshot(path=str(artifacts/'user-dashboard-desktop.png'),full_page=True)
        page.get_by_role('button',name='Tank Management',exact=True).click()
        page.get_by_role('button',name='Add tank',exact=True).click()
        form=page.locator('#formDialog')
        form.locator('[name=name]').fill('Browser added tank')
        expect(form.locator('[name=tank_id]')).to_have_value('TANK-03')
        expect(form.locator('[name=tank_id]')).to_have_attribute('readonly','')
        form.locator('[name=current_count]').fill('100')
        form.get_by_role('button',name='Create tank',exact=True).click()
        expect(form).not_to_be_visible()
        card=page.locator('[data-monitor-tank="TANK-03"]')
        expect(card.get_by_role('button',name='Stock fish',exact=True)).to_have_count(0)
        expect(card.get_by_role('button',name='Mortality check',exact=True)).to_have_count(0)
        card.get_by_role('button',name='Edit Tank',exact=True).click()
        form.locator('[name=current_count]').fill('140')
        form.locator('[name=adjustment_note]').fill('Independently verified population')
        form.get_by_role('button',name='Save tank',exact=True).click()
        expect(form).not_to_be_visible()
        expect(card.locator('[data-monitor-field=saved]')).to_contain_text('140')
        # A background population change while editing feeding inputs must survive Save.
        card.get_by_role('button',name='Edit Tank',exact=True).click()
        page.evaluate("api('/api/tanks/TANK-03/mortality',{method:'POST',body:{count:5}})")
        form.locator('[name=avg_weight_g]').fill('5')
        form.get_by_role('button',name='Save tank',exact=True).click()
        expect(form).not_to_be_visible()
        expect(card.locator('[data-monitor-field=saved]')).to_contain_text('135')
        page.get_by_role('button',name='Food Management',exact=True).click()
        expect(page.get_by_role('heading',name="Today's estimated feed requirements",exact=True)).to_be_visible()
        expect(page.get_by_role('button',name='Record purchase',exact=True)).to_have_count(0)
        expect(page.get_by_role('button',name='Record feeding',exact=True)).to_have_count(0)
        expect(page.locator('.feed-card')).to_have_count(0)
        expect(page.locator('main')).to_contain_text('Seven-day feed estimate')
        expect(page.locator('main')).to_contain_text('Configured average weight')
        page.screenshot(path=str(artifacts/'user-food-desktop.png'),full_page=True)
        page.get_by_role('button',name='Dispersal Management',exact=True).click()
        page.get_by_role('button',name='Record dispersal',exact=True).click()
        form.locator('[name=tank_id]').select_option('TANK-03')
        form.locator('[name=dispersal_id]').fill('UI-SALE-01')
        form.locator('[name=count]').fill('20')
        form.locator('[name=recipient]').fill('Browser test buyer')
        form.locator('[name=unit_price_php]').fill('2')
        form.get_by_role('button',name='Confirm dispersal',exact=True).click()
        expect(form).not_to_be_visible()
        expect(page.locator('tbody')).to_contain_text('UI-SALE-01')
        page.get_by_role('button',name='Analytics & Reports',exact=True).click()
        expect(page.get_by_role('heading',name='Daily mortality records')).to_be_visible()
        page.locator('#filterTank').select_option('TANK-03')
        expect(page.locator('main')).to_contain_text('N/A')
        page.locator('#filterMetric').select_option('population')
        page.screenshot(path=str(artifacts/'user-analytics-desktop.png'),full_page=True)
        page.set_viewport_size({'width':390,'height':844})
        page.get_by_role('button',name='Open navigation').click()
        page.get_by_role('button',name='Dashboard',exact=True).click()
        expect(page.get_by_role('heading',name='Dashboard')).to_be_visible()
        assert page.evaluate('document.documentElement.scrollWidth <= innerWidth'), 'Mobile page overflows horizontally'
        page.screenshot(path=str(artifacts/'user-dashboard-mobile.png'),full_page=True)
        page.get_by_role('button',name='Open navigation').click()
        page.get_by_role('button',name='Tank Management',exact=True).click()
        expect(page.get_by_role('heading',name='Tank Management',exact=True)).to_be_visible()
        page.screenshot(path=str(artifacts/'user-tanks-mobile.png'),full_page=True)
        page.set_viewport_size({'width':1440,'height':1000})
        page.get_by_role('button',name='Sign out',exact=True).click()
        expect(page.locator('#username')).to_be_visible()
        page.locator('#username').fill('preview-admin')
        page.locator('#password').fill('Preview admin password!')
        page.get_by_role('button',name='Sign in',exact=True).click()
        expect(page.get_by_role('heading',name='Farm administration',exact=True)).to_be_visible()
        page.screenshot(path=str(artifacts/'admin-dashboard-desktop.png'),full_page=True)
        page.get_by_role('button',name='Farms & Accounts',exact=True).click()
        expect(page.locator('main')).to_contain_text('Browser test farm')
        page.get_by_role('button',name='Create farmer account',exact=True).click()
        form.locator('[name=display_name]').fill('Browser new farmer')
        form.locator('[name=farm_name]').fill('Browser second farm')
        form.locator('[name=username]').fill('browser-new-farmer')
        form.locator('[name=password]').fill('Browser farmer password!')
        form.get_by_role('button',name='Create private farm & account',exact=True).click()
        expect(form).not_to_be_visible()
        expect(page.locator('main')).to_contain_text('Browser second farm')
        page.get_by_role('button',name='Benchmarks',exact=True).click()
        expect(page.get_by_role('heading',name='Benchmarks',exact=True)).to_be_visible()
        assert 'yolo' not in page.locator('body').inner_text().lower()
        page.screenshot(path=str(artifacts/'admin-benchmarks-desktop.png'),full_page=True)
        browser.close()
    if errors:
        raise AssertionError('Browser JavaScript errors: '+json.dumps(errors))
    print('Browser checks passed: farmer forms, feeding estimates, filtered analytics, mobile overflow, Admin dashboard and account creation.')
    print('Screenshots:',artifacts)


if __name__=='__main__':
    main()
