"""Tank controls and two viewers of one Production worker, using --display-fixture."""
import argparse
import json
from pathlib import Path

from playwright.sync_api import sync_playwright,expect


def main():
    parser=argparse.ArgumentParser()
    parser.add_argument('--url',default='http://127.0.0.1:8001')
    parser.add_argument('--executable',required=True)
    args=parser.parse_args()
    artifacts=Path(__file__).resolve().parents[1]/'private_data'/'browser_qa'
    artifacts.mkdir(parents=True,exist_ok=True)
    errors=[]
    with sync_playwright() as playwright:
        browser=playwright.chromium.launch(headless=True,executable_path=args.executable)
        farmer=browser.new_page(viewport={'width':1440,'height':1000})
        admin=browser.new_page(viewport={'width':1440,'height':1000})
        for page in (farmer,admin):page.on('pageerror',lambda error:errors.append(str(error)))
        def login(page,user,password):
            page.goto(args.url+'/login')
            page.locator('#username').fill(user);page.locator('#password').fill(password)
            page.get_by_role('button',name='Sign in',exact=True).click()
        def alpha(page,selector):
            return page.evaluate("selector=>{const c=document.querySelector(selector);return [...c.getContext('2d').getImageData(0,0,c.width,c.height).data].filter((_,i)=>i%4===3).some(v=>v>0);}",selector)
        login(admin,'preview-admin','Preview admin password!')
        expect(admin.get_by_role('heading',name='Farm administration',exact=True)).to_be_visible()
        admin.evaluate("api('/api/admin/production',{method:'PUT',body:{enabled:false}})")
        login(farmer,'preview-farmer','Preview farmer password!')
        expect(farmer.get_by_role('heading',name='Dashboard',exact=True)).to_be_visible()
        expect(farmer.locator('.production-panel')).to_have_count(0)
        farmer.get_by_role('button',name='Tank Management',exact=True).click()
        expect(farmer.get_by_role('heading',name='Tank Management',exact=True)).to_be_visible()
        assert 'Production Mode' not in farmer.locator('main').inner_text()
        original=farmer.evaluate("api('/api/reports').then(r=>r.tanks.find(t=>t.tank_id==='TANK-01').camera_source)")
        first=farmer.locator('[data-monitor-tank=TANK-01]')
        form=farmer.locator('#formDialog')
        def edit():first.get_by_role('button',name='Edit Tank',exact=True).click()
        def save():
            form.get_by_role('button',name='Save tank',exact=True).click()
            expect(form).not_to_be_visible()
        edit()
        expect(form.locator('[name=source_type]')).to_have_value('saved')
        assert form.locator('[name=source_type] option').all_text_contents()==['No source','USB camera','Network camera','Upload video','Saved video']
        for label,phrase in [('Configured average weight (g)','representative sample'),('Tank capacity (fish)','planned maximum'),('Tank code','Permanent code')]:
            form.get_by_role('button',name='Help for '+label,exact=True).hover()
            expect(farmer.get_by_role('tooltip')).to_contain_text(phrase)
        form.locator('[name=source_type]').select_option('usb')
        expect(form.locator('[name=local_camera]')).to_be_visible()
        expect(form.locator('[name=rtsp_address]')).not_to_be_visible()
        form.locator('[name=local_camera]').select_option('2');save()
        config=farmer.evaluate("api('/api/monitoring').then(r=>r.tanks.find(t=>t.tank_id==='TANK-01'))")
        assert config['live_source']=='2' and config['demonstration_source']=='2' and config['video_source']==original
        edit();form.locator('[name=source_type]').select_option('rtsp')
        expect(form.locator('[name=local_camera]')).not_to_be_visible()
        form.locator('[name=rtsp_address]').fill('rtsp://test-camera/live');save()
        edit();form.locator('[name=source_type]').select_option('upload')
        form.locator('[name=video_upload]').set_input_files({'name':'uploaded-preview.mp4','mimeType':'video/mp4','buffer':Path(original).read_bytes()})
        save()
        config=farmer.evaluate("api('/api/monitoring').then(r=>r.tanks.find(t=>t.tank_id==='TANK-01'))")
        assert config['live_source']=='rtsp://test-camera/live' and config['video_source'].endswith('.mp4')
        edit();expect(form.locator('[name=source_type]')).to_have_value('saved')
        form.locator('[name=source_type]').select_option('none');save()
        config=farmer.evaluate("api('/api/monitoring').then(r=>r.tanks.find(t=>t.tank_id==='TANK-01'))")
        assert config['live_source']=='' and config['demonstration_source']=='' and config['video_source']
        edit();form.locator('[name=source_type]').select_option('rtsp');form.locator('[name=rtsp_address]').fill('rtsp://test-camera/live');save()
        edit();form.locator('[name=source_type]').select_option('saved');form.locator('[name=video_source]').select_option(original);save()
        first.get_by_role('button',name='Play video',exact=True).click()
        farmer.wait_for_function("freshMonitoring(tankStream('TANK-01')) && !!tankStream('TANK-01').data.raw_frame")
        farmer.evaluate("window.originalSocket=tankStream('TANK-01').ws")
        first.locator('.monitoring-preview').click()
        expect(farmer.locator('#tankInspectorHost #countDialog')).to_be_visible()
        farmer.wait_for_function("document.querySelector('#countPreview').naturalWidth>0")
        farmer.wait_for_function("[...document.querySelector('#countOverlay').getContext('2d').getImageData(0,0,640,480).data].some((v,i)=>i%4===3 && v>0)")
        farmer.get_by_role('button',name='Record dispersal',exact=True).click()
        expect(form.locator('[name=tank_id]')).to_have_value('TANK-01')
        form.get_by_role('button',name='Cancel',exact=True).click()
        farmer.locator('.display-options summary').click()
        farmer.get_by_role('button',name='Clean video',exact=True).click()
        assert not alpha(farmer,'#countOverlay')
        farmer.evaluate('refresh()')
        expect(farmer.locator('.display-options')).to_have_attribute('open','')
        assert farmer.evaluate("window.originalSocket===tankStream('TANK-01').ws")
        farmer.keyboard.press('Escape')
        farmer.evaluate('window.scrollTo(0,0)')
        farmer.screenshot(path=str(artifacts/'tank-inspector-clean-desktop.png'),full_page=True)
        farmer.reload()
        expect(farmer.get_by_role('heading',name='Tank Management',exact=True)).to_be_visible()
        farmer.locator('.display-options summary').click()
        expect(farmer.locator('[data-display-choice=show_boxes]')).not_to_be_checked()
        farmer.evaluate('stopAllMonitoring()')
        farmer.wait_for_function("[...State.streams.values()].every(e=>!isMonitoring(e))")
        # Real background processing of an opt-in virtual source; both viewers share it.
        assert farmer.evaluate("api('/api/reports').then(r=>r.tanks.some(t=>t.tank_id==='VIEW-01'))"), 'Start preview with --display-fixture.'
        admin.evaluate("api('/api/admin/production',{method:'PUT',body:{enabled:true}})")
        admin.locator('#farmSelector').select_option(label='Browser test farm')
        expect(admin.get_by_role('heading',name='Dashboard',exact=True)).to_be_visible()
        admin.get_by_role('button',name='Tank Management',exact=True).click()
        farmer.evaluate('refresh()')
        for page in (farmer,admin):
            page.wait_for_function("freshMonitoring(tankStream('VIEW-01')) && !!tankStream('VIEW-01').data.raw_frame",timeout=60000)
        before=farmer.evaluate("api('/api/reports').then(r=>r.total_population)")
        expect(farmer.locator('.production-panel')).to_have_count(0)
        assert 'Production Mode' not in farmer.locator('main').inner_text()
        first.get_by_role('button',name='Edit Tank',exact=True).click()
        assert form.locator('[name=source_type] option').all_text_contents()==['No source','USB camera','Network camera']
        expect(form.locator('[name=source_type]')).to_have_value('rtsp')
        expect(form.locator('[name=rtsp_address]')).to_have_value('rtsp://test-camera/live')
        expect(form.locator('[name=video_upload]')).to_have_count(0)
        form.get_by_role('button',name='Cancel',exact=True).click()
        view=farmer.locator('[data-monitor-tank=VIEW-01]')
        other=admin.locator('[data-monitor-tank=VIEW-01]')
        farmer.wait_for_function("document.querySelector('[data-monitor-tank=VIEW-01] img').naturalWidth>0")
        admin.wait_for_function("document.querySelector('[data-monitor-tank=VIEW-01] canvas').width===640")
        assert not alpha(farmer,'[data-monitor-tank=VIEW-01] canvas')
        assert alpha(admin,'[data-monitor-tank=VIEW-01] canvas')
        for page in (farmer,admin):
            page.evaluate("()=>{window.sharedFrames={};const ws=tankStream('VIEW-01').ws;const original=ws.onmessage;ws.onmessage=event=>{const d=JSON.parse(event.data);if(d.raw_frame)sharedFrames[d.frame_idx]=d.raw_frame;original(event);};}")
        farmer.locator('.display-options').evaluate('(e)=>e.open=true')
        farmer.locator('[data-display-choice=show_conf]').check()
        farmer.wait_for_timeout(3000)
        a=farmer.evaluate('sharedFrames');b=admin.evaluate('sharedFrames')
        common=set(a)&set(b)
        assert common and all(a[key]==b[key] for key in common)
        expect(admin.locator('[data-display-choice=show_conf]')).not_to_be_checked()
        assert alpha(farmer,'[data-monitor-tank=VIEW-01] canvas')
        farmer.get_by_role('button',name='Clean video',exact=True).click()
        view.locator('.monitoring-preview').click()
        expect(farmer.locator('#inspectedTank')).to_have_value('VIEW-01')
        farmer.keyboard.press('Escape')
        farmer.evaluate('window.scrollTo(0,0)')
        farmer.screenshot(path=str(artifacts/'production-inspector-desktop.png'),full_page=True)
        farmer.set_viewport_size({'width':390,'height':844})
        farmer.wait_for_function("document.querySelector('#sidebar').getBoundingClientRect().right<=0")
        farmer.evaluate('window.scrollTo(0,0)')
        assert farmer.evaluate('document.documentElement.scrollWidth<=innerWidth')
        farmer.screenshot(path=str(artifacts/'production-inspector-mobile.png'),full_page=True)
        assert farmer.evaluate("api('/api/reports').then(r=>r.total_population)")==before
        admin.evaluate("api('/api/admin/production',{method:'PUT',body:{enabled:false}})")
        farmer.evaluate('refresh()')
        assert farmer.evaluate("State.report.tanks.find(t=>t.tank_id==='TANK-01').camera_source")==original
        browser.close()
    if errors:raise AssertionError(json.dumps(errors))
    print('Passed: dropdown branches, camera/video retention, field help, inspector continuity, private persistent overlays, shared Production frames, clean video, mobile and unchanged inventory.')


if __name__=='__main__':main()
